name: Update Profile Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Repo & Commit Stats
        id: stats
        run: |
          REPOS=$(curl -s https://api.github.com/users/${{ github.repository_owner }} | jq '.public_repos')
          COMMITS=$(curl -s "https://api.github.com/search/commits?q=author:${{ github.repository_owner }}" -H "Accept: application/vnd.github.cloak-preview" | jq '.total_count')

          echo "Fetching all repositories..."
          mkdir repos
          cd repos
          REPO_NAMES=$(curl -s "https://api.github.com/users/${{ github.repository_owner }}/repos?per_page=100" | jq -r '.[].clone_url')

          TOTAL_LINES=0
          for REPO in $REPO_NAMES; do
            git clone --depth=1 "$REPO" temp_repo >/dev/null 2>&1
            if [ -d "temp_repo" ]; then
              LINES=$(cd temp_repo && git ls-files | xargs wc -l | tail -n1 | awk '{print $1}')
              TOTAL_LINES=$((TOTAL_LINES + LINES))
              rm -rf temp_repo
            fi
          done
          cd ..

          echo "REPOS=$REPOS" >> $GITHUB_ENV
          echo "COMMITS=$COMMITS" >> $GITHUB_ENV
          echo "TOTAL_LINES=$TOTAL_LINES" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s/· Repositories....................[0-9]*/· Repositories....................$REPOS/" README.md
          sed -i "s/· Commits...........................[0-9]*/· Commits...........................$COMMITS/" README.md
          sed -i "s/· Total lines of code...............[0-9]*/· Total lines of code...............$TOTAL_LINES/" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated profile stats" || exit 0  # Avoid failing if no changes
          git push
